#--------------------------------------------------------------------------------
# Values for this lesson - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
title         : "Using Jekyll"
repo          : "http://github.com/gvwilson/using-jekyll"
site          : "http://gvwilson.github.io/using-jekyll"
#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
swc_blog      : "http://software-carpentry.org/feed.xml"
swc_contact   : "admin@software-carpentry.org"
swc_files     : "http://files.software-carpentry.org"
swc_github    : "http://github.com/swcarpentry"
swc_site      : "http://software-carpentry.org"
swc_twitter   : "http://twitter.com/swcarpentry"
#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
